### ISSUE TITLE
 [FR] Отрисовка основной структуры данных (граф/дерево)

### ISSUE THREAD

**Issue by imperio008** [imperio008/Dijkstra#5]

**Comment by nurik897** [comment]
В процессе создания.
Были испробованы и отброшены реализации через swing и awt
На данный момент реализуется через javafx

**Comment by nurik897** [comment]
Первые основные таблицы залиты

**Comment by nurik897** [comment]
Готово

**Comment by nurik897** [comment]
Задача выполнена
Отрисовка находится в классе Controller
