### ISSUE TITLE
[FR] Реализация алгорима 

### ISSUE THREAD

**Issue by imperio008** [imperio008/Dijkstra#6]

**Comment by nurik897** [comment]
Алгоритм реализован, теперь задача состоит в том, чтобы связать его с UI.
Также придется разбивать алгоритм на небольшие участки, чтобы была возможность реализовать пошаговую работу.

**Comment by nurik897** [comment]
Тк основная задача выполнена, закрываю

**Comment by imperio008** [comment]
реализация в файле Dijkstra.java
